||prizes.giftstoday.site/*
||wowmovie.me/main.js
||vjs.zencdn.net/ie8/*/*.js
||894de8bb784.com/929095/*
||123moviesfree.com/ip.temp/at_001/js/jquery.hover-intent.js
||123moviesfree.com/ip.temp/at_001/js/slide.min.js
||123moviesfree.com/ip.temp/at_001/js/ipmovies.min.js
||justdating.online/*
||894de8bb784.com/*
||srv.bebi.com/*
||www.toonova.net/scripts/front/search.js
||www.mgid.com##[src^="data:"]
||gomovies.to##[src^="data:"]
||123movies.to##[src^="data:"]
||20a840a14a0ef7d6.com/*
||20a840a14a0ef7d6.com
||openload.co/assets/js/script.*
||openload.co/assets/js/license.5.js
||imgg-cdn.adskeeper.co.uk/*
||c.adskeeper.co.uk/*
||rlqvyqgjkxgx.com/*
||bet365.com/*
||104.198.61.4/*
||jbjcv.com/*
||http://rlqvyqgjkxgx.com/*
||mg.adskeeper.co.uk/*
||https://go.padsdel.com/ajs.php
!||https://go.padsdel.com/*
!||go.padsdel.com/ajs.php^*
||ajax.cloudflare.com/cdn-cgi/nexp/*
||static.beeg.com/js/ads/ads.js
!||static.beeg.com/cpl/2096.js
||www.toonova.net###M_AD
||www.toonova.net###Mad
||www.toonova.net###mini-announcement
||www.toonova.net###content > .info_block
||www.toonova.net###disqus_thread
||www.toonova.net###eps_blocks
||gomovies.to###main > .container > .main-detail.main-content > .main-category.main-content > .content-kuss
||https://onclkds.com/apu.php*
||openload.co###exoNativeWidget2554079
https://ads.exdynsrv.com/*
https://go.padsdel.com/*